# Generated by Django 4.0 on 2023-03-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_order_date_time_order_end_date_order_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(max_length=100000),
        ),
    ]
