# Generated by Django 4.0 on 2023-03-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_order_end_date_alter_order_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
